# Generated by Django 4.2.5 on 2023-09-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionality', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('age', models.IntegerField()),
                ('ht', models.IntegerField()),
                ('kg', models.IntegerField()),
                ('nacionality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.nacionality')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.sport')),
            ],
        ),
    ]
